[1]
main_mode = "rtu-monitor"
tcp_port = 502
tcp_host = "127.0.0.1"
unit = 1
holding_count = 512
coil_count = 512
discrete_count = 512
input_count = 512
client_tick_ms = 200
ui_tick_ms = 10
device = "dev/null"
baudrate = 9600
databits = 8
parity = "n"
stopbits = 1
flow = "none"
reg_format = ""

[1.labels]
0 = "???"

[1.reg_combinations]

[1.swap_bytes_reg]

[1.swap_words_reg]

[testss]
main_mode = "tcp-client"
tcp_port = 502
tcp_host = "127.0.0.1"
unit = 1
holding_count = 512
coil_count = 512
discrete_count = 512
input_count = 512
client_tick_ms = 200
ui_tick_ms = 10
device = "dev/null"
baudrate = 9600
databits = 8
parity = "n"
stopbits = 1
flow = "none"
reg_format = "u16"

[testss.labels]

[testss.reg_combinations]

[testss.swap_bytes_reg]

[testss.swap_words_reg]

["hahaha 你是谁啊"]
main_mode = "rtu-client"
tcp_port = 502
tcp_host = "127.0.0.1"
unit = 1
holding_count = 512
coil_count = 512
discrete_count = 512
input_count = 512
client_tick_ms = 200
ui_tick_ms = 10
device = "dev/null"
baudrate = 9600
databits = 8
parity = "n"
stopbits = 1
flow = "none"
reg_format = ""

["hahaha 你是谁啊".labels]

["hahaha 你是谁啊".reg_combinations]

["hahaha 你是谁啊".swap_bytes_reg]

["hahaha 你是谁啊".swap_words_reg]

[3030]
main_mode = "tcp-client"
tcp_port = 10699
tcp_host = "127.0.0.1"
unit = 1
holding_count = 512
coil_count = 512
discrete_count = 512
input_count = 512
client_tick_ms = 200
ui_tick_ms = 10
device = "dev/null"
baudrate = 9600
databits = 8
parity = "n"
stopbits = 1
flow = "none"
reg_format = ""

[3030.labels]

[3030.reg_combinations]
10 = "i16"
12 = "i16"
14 = "hex"
7 = "i16"

[3030.swap_bytes_reg]

[3030.swap_words_reg]

[m]
main_mode = "tcp-client"
tcp_port = 10699
tcp_host = "127.0.0.1"
unit = 1
holding_count = 512
coil_count = 512
discrete_count = 512
input_count = 512
client_tick_ms = 200
ui_tick_ms = 10
device = "dev/null"
baudrate = 9600
databits = 8
parity = "n"
stopbits = 1
flow = "none"
reg_format = ""

[m.labels]

[m.reg_combinations]
10 = "i16"
12 = "i16"
7 = "i16"
14 = "hex"

[m.swap_bytes_reg]

[m.swap_words_reg]

[tcp-client]
main_mode = "tcp-client"
tcp_port = 10688
tcp_host = "127.0.0.1"
unit = 1
holding_count = 512
coil_count = 512
discrete_count = 512
input_count = 512
client_tick_ms = 200
ui_tick_ms = 10
device = "dev/null"
baudrate = 9600
databits = 8
parity = "n"
stopbits = 1
flow = "none"
reg_format = ""

[tcp-client.labels]
0 = "1233"

[tcp-client.reg_combinations]

[tcp-client.swap_bytes_reg]

[tcp-client.swap_words_reg]

[v317-eth]
main_mode = "tcp-client"
tcp_port = 502
tcp_host = "172.16.6.73"
unit = 1
holding_count = 512
coil_count = 512
discrete_count = 512
input_count = 512
client_tick_ms = 200
ui_tick_ms = 10
device = "dev/null"
baudrate = 9600
databits = 8
parity = "n"
stopbits = 1
flow = "none"
reg_format = "u16"

[v317-eth.labels]

[v317-eth.reg_combinations]

[v317-eth.swap_bytes_reg]

[v317-eth.swap_words_reg]

[hello]
main_mode = "tcp-client"
tcp_port = 502
tcp_host = "127.0.0.1"
unit = 1
holding_count = 512
coil_count = 512
discrete_count = 512
input_count = 512
client_tick_ms = 200
ui_tick_ms = 10
device = "dev/null"
baudrate = 9600
databits = 8
parity = "n"
stopbits = 1
flow = "none"
reg_format = ""

[hello.labels]

[hello.reg_combinations]

[hello.swap_bytes_reg]

[hello.swap_words_reg]

[__default__]
main_mode = "tcp-client"
tcp_port = 502
tcp_host = "127.0.0.1"
unit = 1
holding_count = 512
coil_count = 512
discrete_count = 512
input_count = 512
client_tick_ms = 200
ui_tick_ms = 10
device = "dev/null"
baudrate = 9600
databits = 8
parity = "n"
stopbits = 1
flow = "none"
reg_format = "u16"

[__default__.labels]

[__default__.reg_combinations]

[__default__.swap_bytes_reg]

[__default__.swap_words_reg]

[fkm]
main_mode = "tcp-client"
tcp_port = 10699
tcp_host = "127.0.0.1"
unit = 1
holding_count = 512
coil_count = 512
discrete_count = 512
input_count = 512
client_tick_ms = 200
ui_tick_ms = 10
device = "dev/null"
baudrate = 9600
databits = 8
parity = "n"
stopbits = 1
flow = "none"
reg_format = ""

[fkm.labels]

[fkm.reg_combinations]

[fkm.swap_bytes_reg]

[fkm.swap_words_reg]

[test]
main_mode = "tcp-client"
tcp_port = 502
tcp_host = "127.0.0.1"
unit = 1
holding_count = 512
coil_count = 512
discrete_count = 512
input_count = 512
client_tick_ms = 200
ui_tick_ms = 10
device = "dev/null"
baudrate = 9600
databits = 8
parity = "n"
stopbits = 1
flow = "none"
reg_format = ""

[test.labels]

[test.reg_combinations]

[test.swap_bytes_reg]

[test.swap_words_reg]

[my-monitor]
main_mode = "tcp-monitor"
tcp_port = 502
tcp_host = "127.0.0.1"
unit = 1
holding_count = 64
coil_count = 64
discrete_count = 64
input_count = 64
client_tick_ms = 500
ui_tick_ms = 10
device = "dev/null"
baudrate = 9600
databits = 8
parity = "n"
stopbits = 1
flow = "none"
reg_format = ""

[my-monitor.labels]

[my-monitor.reg_combinations]

[my-monitor.swap_bytes_reg]

[my-monitor.swap_words_reg]

[tcp-master]
main_mode = "ts"
tcp_port = 10688
tcp_host = "127.0.0.1"
unit = 1
holding_count = 512
coil_count = 512
discrete_count = 512
input_count = 512
client_tick_ms = 200
ui_tick_ms = 10
device = "dev/null"
baudrate = 9600
databits = 8
parity = "n"
stopbits = 1
flow = "none"
reg_format = ""

[tcp-master.labels]

[tcp-master.reg_combinations]

[tcp-master.swap_bytes_reg]

[tcp-master.swap_words_reg]

[tcp-server]
main_mode = "tcp-server"
tcp_port = 10699
tcp_host = "127.0.0.1"
unit = 1
holding_count = 512
coil_count = 512
discrete_count = 512
input_count = 512
client_tick_ms = 200
ui_tick_ms = 10
device = "dev/null"
baudrate = 9600
databits = 8
parity = "n"
stopbits = 1
flow = "none"
reg_format = ""

[tcp-server.labels]

[tcp-server.reg_combinations]

[tcp-server.swap_bytes_reg]

[tcp-server.swap_words_reg]

[tcp-client2]
main_mode = "tcp-client"
tcp_port = 10699
tcp_host = "127.0.0.1"
unit = 1
holding_count = 512
coil_count = 512
discrete_count = 512
input_count = 512
client_tick_ms = 200
ui_tick_ms = 10
device = "dev/null"
baudrate = 9600
databits = 8
parity = "n"
stopbits = 1
flow = "none"
reg_format = ""

[tcp-client2.labels]

[tcp-client2.reg_combinations]

[tcp-client2.swap_bytes_reg]

[tcp-client2.swap_words_reg]
